#pragma once
#include <Windows.h>
#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <iostream>
#include <stdio.h>
#include <vector>
#include <queue>
#include <fstream>
#include <ostream>
#include <vector>
#include <thread>